PACKAGE_NAME="hp-omen-extra"
PACKAGE_VERSION="2.1.2"
MAKE[0]="grep -iq clang /proc/version && make LLVM=1 -C \$kernel_source_dir M=\$dkms_tree/\$module/\$module_version/build EXTRA_CFLAGS='' modules || make -C \$kernel_source_dir M=\$dkms_tree/\$module/\$module_version/build EXTRA_CFLAGS='' modules"
CLEAN=true
BUILT_MODULE_NAME[0]="hp-wmi"
DEST_MODULE_LOCATION[0]="/kernel/drivers/platform/x86/hp"
BUILT_MODULE_NAME[1]="hp-omen-extra"
DEST_MODULE_LOCATION[1]="/kernel/drivers/platform/x86/hp"
AUTOINSTALL="yes"
